version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: config/Api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - static-volume:/usr/src/app/src/static
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ADMIN_PASSWORD=your-password
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./static:/usr/share/nginx/html
      - ./certbot-data:/data/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/data/letsencrypt --email me@cabraljv.dev --agree-tos --no-eff-email -d labs.cabraljv.dev
  update-static-worker:
    build: 
      context: .
      dockerfile: config/UpdateStaticWorker/Dockerfile
    volumes:
      - static-volume:/usr/src/app/src/static
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  unprocessed-items-worker:
    build: 
      context: .
      dockerfile: config/UnprocessedItemsWorker/Dockerfile
    volumes:
      - static-volume:/usr/src/app/src/static
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
volumes:
  static-volume:
  redis-data:
